// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Insfrastructure.Migrations
{
    [DbContext(typeof(FsContext))]
    [Migration("20251201105540_add-candidate-entity")]
    partial class addcandidateentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.CandDocs.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CandNumber")
                        .HasColumnType("int");

                    b.Property<int>("CentreCode")
                        .HasColumnType("int");

                    b.Property<int>("Session")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("Domain.Entities.CandDocs.CandidateDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CandidateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CentreCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExamCenterId")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormCentreCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("OcrText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Session")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExamCenterId");

                    b.HasIndex("UserId");

                    b.ToTable("CandidateDocuments");
                });

            modelBuilder.Entity("Domain.Entities.CandDocs.ExamCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CenterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CenterNumber")
                        .HasColumnType("int");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubDivision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExamCenters");
                });

            modelBuilder.Entity("Domain.Entities.CandDocs.ImportError", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CandidateDocumentId")
                        .HasColumnType("int");

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CandidateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Session")
                        .HasColumnType("int");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateDocumentId");

                    b.ToTable("ImportErrors");
                });

            modelBuilder.Entity("Domain.Entities.Configurations.Archive", b =>
                {
                    b.Property<int>("ArchiveID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArchiveID"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileBase64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArchiveID");

                    b.ToTable("Archives");
                });

            modelBuilder.Entity("Domain.Entities.Configurations.Branch", b =>
                {
                    b.Property<int>("BranchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchID"));

                    b.Property<int>("AdressID")
                        .HasColumnType("int");

                    b.Property<string>("BranchAbbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.HasKey("BranchID");

                    b.HasIndex("AdressID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("Domain.Entities.Configurations.Company", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyID"));

                    b.Property<int?>("AdressID")
                        .HasColumnType("int");

                    b.Property<int?>("ArchiveID")
                        .HasColumnType("int");

                    b.Property<string>("CompanyAbbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyID");

                    b.HasIndex("AdressID");

                    b.HasIndex("ArchiveID");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Domain.Entities.Configurations.Job", b =>
                {
                    b.Property<int>("JobID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobID"));

                    b.Property<string>("JobCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobID");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Domain.Entities.Localisation.Adress", b =>
                {
                    b.Property<int>("AdressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdressID"));

                    b.Property<string>("AdressCellNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdressEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdressFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdressFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdressPOBox")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdressPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdressWebSite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QuarterID")
                        .HasColumnType("int");

                    b.HasKey("AdressID");

                    b.HasIndex("QuarterID");

                    b.ToTable("Adresses");
                });

            modelBuilder.Entity("Domain.Entities.Localisation.Country", b =>
                {
                    b.Property<int>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryID"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CountryLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryID");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Domain.Entities.Localisation.Quarter", b =>
                {
                    b.Property<int>("QuarterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuarterID"));

                    b.Property<string>("QuarterCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QuarterLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TownID")
                        .HasColumnType("int");

                    b.HasKey("QuarterID");

                    b.HasIndex("TownID");

                    b.ToTable("Quarters");
                });

            modelBuilder.Entity("Domain.Entities.Localisation.Region", b =>
                {
                    b.Property<int>("RegionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionID"));

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RegionLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegionID");

                    b.HasIndex("CountryID");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("Domain.Entities.Localisation.Town", b =>
                {
                    b.Property<int>("TownID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TownID"));

                    b.Property<int>("RegionID")
                        .HasColumnType("int");

                    b.Property<string>("TownCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TownLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TownID");

                    b.HasIndex("RegionID");

                    b.ToTable("Towns");
                });

            modelBuilder.Entity("Domain.Entities.Security.ActionMenuProfile", b =>
                {
                    b.Property<int>("ActionMenuProfileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActionMenuProfileID"));

                    b.Property<bool>("Add")
                        .HasColumnType("bit");

                    b.Property<bool>("Delete")
                        .HasColumnType("bit");

                    b.Property<int>("MenuID")
                        .HasColumnType("int");

                    b.Property<int>("ProfileID")
                        .HasColumnType("int");

                    b.Property<bool>("Update")
                        .HasColumnType("bit");

                    b.HasKey("ActionMenuProfileID");

                    b.HasIndex("MenuID");

                    b.HasIndex("ProfileID");

                    b.ToTable("ActionMenuProfiles");
                });

            modelBuilder.Entity("Domain.Entities.Security.ActionSubMenuProfile", b =>
                {
                    b.Property<int>("ActionSubMenuProfileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActionSubMenuProfileID"));

                    b.Property<bool>("Add")
                        .HasColumnType("bit");

                    b.Property<bool>("Delete")
                        .HasColumnType("bit");

                    b.Property<int>("ProfileID")
                        .HasColumnType("int");

                    b.Property<int>("SubMenuID")
                        .HasColumnType("int");

                    b.Property<bool>("Update")
                        .HasColumnType("bit");

                    b.HasKey("ActionSubMenuProfileID");

                    b.HasIndex("ProfileID");

                    b.HasIndex("SubMenuID");

                    b.ToTable("ActionSubMenuProfiles");
                });

            modelBuilder.Entity("Domain.Entities.Security.GlobalPerson", b =>
                {
                    b.Property<int>("GlobalPersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GlobalPersonID"));

                    b.Property<int>("AdressID")
                        .HasColumnType("int");

                    b.Property<string>("CNI")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tiergroup")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GlobalPersonID");

                    b.HasIndex("AdressID");

                    b.ToTable("GlobalPeople", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Security.Menu", b =>
                {
                    b.Property<int>("MenuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuID"));

                    b.Property<int>("AppearanceOrder")
                        .HasColumnType("int");

                    b.Property<int>("IsShortcut")
                        .HasColumnType("int");

                    b.Property<string>("MenuCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuController")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MenuFlat")
                        .HasColumnType("bit");

                    b.Property<string>("MenuIconName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MenuState")
                        .HasColumnType("bit");

                    b.Property<bool>("MenuStatus")
                        .HasColumnType("bit");

                    b.Property<int>("ModuleID")
                        .HasColumnType("int");

                    b.HasKey("MenuID");

                    b.HasIndex("ModuleID");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("Domain.Entities.Security.Module", b =>
                {
                    b.Property<int>("ModuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuleID"));

                    b.Property<int>("AppearanceOrder")
                        .HasColumnType("int");

                    b.Property<string>("ModuleArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuleCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuleDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuleDisabledImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuleImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuleLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModulePressedImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ModuleState")
                        .HasColumnType("bit");

                    b.Property<bool>("ModuleStatus")
                        .HasColumnType("bit");

                    b.HasKey("ModuleID");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("Domain.Entities.Security.Mouchard", b =>
                {
                    b.Property<int>("MouchardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MouchardID"));

                    b.Property<int?>("BranchID")
                        .HasColumnType("int");

                    b.Property<string>("MoucharAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MoucharBusinessDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MoucharDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MoucharDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoucharHost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoucharHostAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoucharOperationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoucharProcedureName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SneackHour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("MouchardID");

                    b.HasIndex("BranchID");

                    b.HasIndex("UserID");

                    b.ToTable("Mouchards");
                });

            modelBuilder.Entity("Domain.Entities.Security.Profile", b =>
                {
                    b.Property<int>("ProfileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfileID"));

                    b.Property<string>("ProfileCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfileLevel")
                        .HasColumnType("int");

                    b.Property<bool>("ProfileState")
                        .HasColumnType("bit");

                    b.HasKey("ProfileID");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Domain.Entities.Security.Sex", b =>
                {
                    b.Property<int>("SexID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SexID"));

                    b.Property<string>("SexCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SexLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SexID");

                    b.ToTable("Sexes");
                });

            modelBuilder.Entity("Domain.Entities.Security.SubMenu", b =>
                {
                    b.Property<int>("SubMenuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubMenuID"));

                    b.Property<int>("AppearanceOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsChortcut")
                        .HasColumnType("bit");

                    b.Property<int>("MenuID")
                        .HasColumnType("int");

                    b.Property<string>("SubMenuCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubMenuController")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubMenuDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubMenuIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubMenuLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubMenuPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SubMenuState")
                        .HasColumnType("bit");

                    b.HasKey("SubMenuID");

                    b.HasIndex("MenuID");

                    b.ToTable("SubMenus");
                });

            modelBuilder.Entity("Domain.Entities.Security.People", b =>
                {
                    b.HasBaseType("Domain.Entities.Security.GlobalPerson");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMarketer")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSeller")
                        .HasColumnType("bit");

                    b.Property<int?>("SexID")
                        .HasColumnType("int");

                    b.HasIndex("SexID");

                    b.ToTable("People", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Security.User", b =>
                {
                    b.HasBaseType("Domain.Entities.Security.People");

                    b.Property<int?>("BranchID")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobID")
                        .HasColumnType("int");

                    b.Property<int?>("ProfileID")
                        .HasColumnType("int");

                    b.Property<int>("UserAccessLevel")
                        .HasColumnType("int");

                    b.Property<bool>("UserAccountState")
                        .HasColumnType("bit");

                    b.Property<string>("UserLogin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("BranchID");

                    b.HasIndex("JobID");

                    b.HasIndex("ProfileID");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CandDocs.CandidateDocument", b =>
                {
                    b.HasOne("Domain.Entities.CandDocs.ExamCenter", "ExamCenter")
                        .WithMany("CandidateDocuments")
                        .HasForeignKey("ExamCenterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamCenter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.CandDocs.ImportError", b =>
                {
                    b.HasOne("Domain.Entities.CandDocs.CandidateDocument", "CandidateDocument")
                        .WithMany("ImportErrors")
                        .HasForeignKey("CandidateDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CandidateDocument");
                });

            modelBuilder.Entity("Domain.Entities.Configurations.Branch", b =>
                {
                    b.HasOne("Domain.Entities.Localisation.Adress", "Adress")
                        .WithMany()
                        .HasForeignKey("AdressID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Configurations.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Adress");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domain.Entities.Configurations.Company", b =>
                {
                    b.HasOne("Domain.Entities.Localisation.Adress", "Adress")
                        .WithMany()
                        .HasForeignKey("AdressID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Configurations.Archive", "Archive")
                        .WithMany()
                        .HasForeignKey("ArchiveID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Adress");

                    b.Navigation("Archive");
                });

            modelBuilder.Entity("Domain.Entities.Localisation.Adress", b =>
                {
                    b.HasOne("Domain.Entities.Localisation.Quarter", "Quarter")
                        .WithMany("Adress")
                        .HasForeignKey("QuarterID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Quarter");
                });

            modelBuilder.Entity("Domain.Entities.Localisation.Quarter", b =>
                {
                    b.HasOne("Domain.Entities.Localisation.Town", "Town")
                        .WithMany("Quarters")
                        .HasForeignKey("TownID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Town");
                });

            modelBuilder.Entity("Domain.Entities.Localisation.Region", b =>
                {
                    b.HasOne("Domain.Entities.Localisation.Country", "Country")
                        .WithMany("Regions")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Domain.Entities.Localisation.Town", b =>
                {
                    b.HasOne("Domain.Entities.Localisation.Region", "Region")
                        .WithMany("Towns")
                        .HasForeignKey("RegionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Domain.Entities.Security.ActionMenuProfile", b =>
                {
                    b.HasOne("Domain.Entities.Security.Menu", "Menu")
                        .WithMany("ActionMenuProfiles")
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Security.Profile", "Profile")
                        .WithMany("ActionMenuProfiles")
                        .HasForeignKey("ProfileID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Domain.Entities.Security.ActionSubMenuProfile", b =>
                {
                    b.HasOne("Domain.Entities.Security.Profile", "Profile")
                        .WithMany("ActionSubMenuProfiles")
                        .HasForeignKey("ProfileID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Security.SubMenu", "SubMenu")
                        .WithMany("ActionSubMenuProfiles")
                        .HasForeignKey("SubMenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("SubMenu");
                });

            modelBuilder.Entity("Domain.Entities.Security.GlobalPerson", b =>
                {
                    b.HasOne("Domain.Entities.Localisation.Adress", "Adress")
                        .WithMany()
                        .HasForeignKey("AdressID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Adress");
                });

            modelBuilder.Entity("Domain.Entities.Security.Menu", b =>
                {
                    b.HasOne("Domain.Entities.Security.Module", "Module")
                        .WithMany("Menus")
                        .HasForeignKey("ModuleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Domain.Entities.Security.Mouchard", b =>
                {
                    b.HasOne("Domain.Entities.Configurations.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Security.SubMenu", b =>
                {
                    b.HasOne("Domain.Entities.Security.Menu", "Menu")
                        .WithMany("SubMenus")
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Domain.Entities.Security.People", b =>
                {
                    b.HasOne("Domain.Entities.Security.GlobalPerson", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Security.People", "GlobalPersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Security.Sex", "Sex")
                        .WithMany()
                        .HasForeignKey("SexID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Sex");
                });

            modelBuilder.Entity("Domain.Entities.Security.User", b =>
                {
                    b.HasOne("Domain.Entities.Configurations.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Security.People", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Security.User", "GlobalPersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Configurations.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Security.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");

                    b.Navigation("Job");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Domain.Entities.CandDocs.CandidateDocument", b =>
                {
                    b.Navigation("ImportErrors");
                });

            modelBuilder.Entity("Domain.Entities.CandDocs.ExamCenter", b =>
                {
                    b.Navigation("CandidateDocuments");
                });

            modelBuilder.Entity("Domain.Entities.Localisation.Country", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("Domain.Entities.Localisation.Quarter", b =>
                {
                    b.Navigation("Adress");
                });

            modelBuilder.Entity("Domain.Entities.Localisation.Region", b =>
                {
                    b.Navigation("Towns");
                });

            modelBuilder.Entity("Domain.Entities.Localisation.Town", b =>
                {
                    b.Navigation("Quarters");
                });

            modelBuilder.Entity("Domain.Entities.Security.Menu", b =>
                {
                    b.Navigation("ActionMenuProfiles");

                    b.Navigation("SubMenus");
                });

            modelBuilder.Entity("Domain.Entities.Security.Module", b =>
                {
                    b.Navigation("Menus");
                });

            modelBuilder.Entity("Domain.Entities.Security.Profile", b =>
                {
                    b.Navigation("ActionMenuProfiles");

                    b.Navigation("ActionSubMenuProfiles");
                });

            modelBuilder.Entity("Domain.Entities.Security.SubMenu", b =>
                {
                    b.Navigation("ActionSubMenuProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
